language: go
go_import_path: github.com/LUSHDigital/spew
go:
    - 1.12.x
    - 1.13.x
    - tip
sudo: false
install: true
env:
  - GOMODULE111=on
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - go test -v -race -tags safe ./...
    - go test -v -race -tags testcgo ./... -covermode=atomic -coverprofile=profile.cov

